### ISSUE TITLE
Failed to load the tidy-markdown package

### ISSUE THREAD

**Issue by kmcginnes** [slang800/atom-tidy-markdown#1]
One noteworthy thing on my machine: I installed atom when I had the default OS X Ruby version selected, and then after I switched to using 1.9.3-p547 system wide using rbenv.

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.3
**Thrown From**: [tidy-markdown](https://github.com/slang800/atom-tidy-markdown) package, v0.1.0
### Stack Trace

Failed to load the tidy-markdown package

```
At Cannot find module 'tidy-markdown'

Error: Cannot find module 'tidy-markdown'
  at Module._resolveFilename (module.js:351:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:383:52)
  at Function.Module._load (module.js:293:25)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/krismcginnes/.atom/packages/tidy-markdown/lib/tidy-markdown.coffee:2:16)
  at Object.<anonymous> (/Users/krismcginnes/.atom/packages/tidy-markdown/lib/tidy-markdown.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/krismcginnes/.atom/packages/tidy-markdown/lib/index.coffee:1:16)
  at Object.<anonymous> (/Users/krismcginnes/.atom/packages/tidy-markdown/lib/index.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:672:34)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:189:28
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app/src/package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:383:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:464:30)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:268:29
  at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:77:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)

```
### Commands

```
     -3:27.4 settings-view:open (atom-text-editor.editor)
     -0:14.1 core:confirm (atom-text-editor.editor.mini)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
tidy-markdown, v0.1.0

# Dev
No dev packages
```

**Comment by notslang** [comment]
That's odd. And this package shouldn't have any Ruby in it (or its dependencies), so that shouldn't matter, right?

Anyway, I'll find an OSX box and try to reproduce this.

**Comment by kmcginnes** [comment]
Yeah, I doubt it has any relevance, but just wanted to mention it.

It installed fine in Windows

**Comment by notslang** [comment]
Oh, and I can reproduce this... working on it right now

**Comment by notslang** [comment]
As a workaround `cd`ing into the directory of the package (`~/.atom/packages/tidy-markdown`) and running `apm install` seems to fix this.

**Comment by notslang** [comment]
I am able to reproduce this on Linux now too ... I had a symlink to my dev directory hanging around that apparently kept this error from happening

**Comment by kmcginnes** [comment]
The work around worked perfectly. Thanks!

I'll leave this open for you to close once you push a change.
