### ISSUE TITLE
Error with three hyphens, will not expand

### ISSUE THREAD

**Issue by brandenbyers** [slang800/atom-tidy-markdown#14]
Every time that I try to save a markdown file with three hyphens, I receive an error. If I change three hyphens to four (`----`), it saves and expands as expected.
1. Type `---` for a markdown line break
2. Save

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [tidy-markdown](https://github.com/slang800/atom-tidy-markdown) package, v1.0.0
### Stack Trace

Uncaught expected '<document start>', but found <scalar>
  on line 3, column 1

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:774

expected '<document start>', but found <scalar>
  on line 3, column 1
  at ParserError.YAMLError (/Users/branden/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/errors.js:70:46)
  at ParserError.MarkedYAMLError (/Users/branden/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/errors.js:90:45)
  at new ParserError (/Users/branden/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/parser.js:17:48)
  at Constructor.Parser.Parser.parse_document_start (/Users/branden/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/parser.js:153:17)
  at Constructor.Parser.Parser.check_event (/Users/branden/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/parser.js:62:48)
  at Constructor.Composer.Composer.get_single_node (/Users/branden/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/composer.js:54:17)
  at Constructor.BaseConstructor.BaseConstructor.get_single_data (/Users/branden/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/constructor.js:77:19)
  at Object.load (/Users/branden/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/yaml.js:112:20)
  at parse (/Users/branden/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/index.js:28:27)
  at extractor (/Users/branden/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/index.js:21:34)
  at module.exports (/Users/branden/.atom/packages/tidy-markdown/node_modules/tidy-markdown/lib/index.coffee:274:13)
  at Object.module.exports.run (/Users/branden/.atom/packages/tidy-markdown/lib/index.coffee:49:17)
  at /Users/branden/.atom/packages/tidy-markdown/lib/index.coffee:30:12
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:740:18)
  at /Users/branden/.atom/packages/tidy-markdown/lib/index.coffee:28:14
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:985:20)
  at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:978:19)
  at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:579:26)
  at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:535:18)
  at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:518:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:592:35)
  at atom-workspace.atom.commands.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace-element.js:311:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```
### Commands

```
     -1:30.6.0 vim-mode:reset-command-mode (atom-text-editor.editor.vim-mode.is-focused.command-mode)
 67x -1:30.4.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  5x -1:27.8.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.command-mode)
 30x -1:27.1.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.command-mode)
 17x -1:25.4.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  5x -1:23.3.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -1:21.4.0 vim-mode:insert-after-end-of-line (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  3x -1:21 markdown-writer:insert-new-line (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -1:13.7.0 vim-mode:activate-command-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode.autocomplete-active)
     -1:12.2.0 core:save (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:03.3.0 core:move-left (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:02.2.0 vim-mode:reset-command-mode (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:02.2.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  2x -0:01.8.0 vim-mode:delete (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:00.9.0 vim-mode:reset-command-mode (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:00.6.0 core:save (atom-text-editor.editor.vim-mode.is-focused.command-mode)
```
### Config

``` json
{
  "core": {
    "themes": [
      "white-ui",
      "sk-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
markdown-scroll-sync, v0.4.0
markdown-writer, v1.5.1
sk-light-syntax, v1.1.2
tidy-markdown, v1.0.0
typewriter, v0.3.3
vim-mode, v0.54.0
white-ui, v2.3.0

# Dev
No dev packages
```

**Comment by notslang** [comment]
working on this in https://github.com/slang800/tidy-markdown/pull/32 (I'm pretty sure that this error was caused by `---` being read as front-matter)
