### ISSUE TITLE
Uncaught while scanning a simple key  on line 2, column 1could not find expected ':'  on line ...

### ISSUE THREAD

**Issue by DaveEveritt** [slang800/atom-tidy-markdown#15]
On saving a Markdown file (either with 'on save' disabled or checked), this is the error:

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [tidy-markdown](https://github.com/slang800/atom-tidy-markdown) package, v1.0.0
### Stack Trace

Uncaught while scanning a simple key
  on line 2, column 1
could not find expected ':'
  on line 4, column 1

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:774

while scanning a simple key
  on line 2, column 1
could not find expected ':'
  on line 4, column 1
    at ScannerError.YAMLError (/Users/admin/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/errors.js:70:46)
    at ScannerError.MarkedYAMLError (/Users/admin/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/errors.js:90:45)
    at new ScannerError (/Users/admin/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/scanner.js:23:49)
    at Constructor.Scanner.Scanner.stale_possible_simple_keys (/Users/admin/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/scanner.js:286:17)
    at Constructor.Scanner.Scanner.need_more_tokens (/Users/admin/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/scanner.js:168:12)
    at Constructor.Scanner.Scanner.check_token (/Users/admin/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/scanner.js:115:19)
    at Constructor.Parser.Parser.parse_block_mapping_value (/Users/admin/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/parser.js:447:19)
    at Constructor.Parser.Parser.check_event (/Users/admin/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/parser.js:62:48)
    at Constructor.Composer.Composer.compose_node (/Users/admin/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/composer.js:73:16)
    at Constructor.Composer.Composer.compose_mapping_node (/Users/admin/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/composer.js:146:27)
```
### Commands

```
     -0:10.7.0 core:move-to-top (atom-text-editor.editor.is-focused)
     -0:10 core:move-down (atom-text-editor.editor.is-focused)
     -0:09.6.0 core:select-down (atom-text-editor.editor.is-focused)
     -0:09.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:08.5.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:08.1.0 linter:set-bubble-transparent (atom-text-editor.editor.is-focused)
     -0:06.5.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
  2x -0:06.2.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:05.3.0 linter:set-bubble-transparent (atom-text-editor.editor.is-focused)
     -0:03.1.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:02.8.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:02.4.0 core:select-down (atom-text-editor.editor.is-focused)
     -0:02.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:01.2.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "archive-view",
      "autoflow",
      "image-view",
      "language-clojure",
      "language-csharp",
      "language-objective-c",
      "language-toml",
      "metrics",
      "package-generator",
      "timecop",
      "language-c",
      "open-on-github",
      "language-xml",
      "language-sql",
      "language-source",
      "language-php",
      "language-make",
      "language-java",
      "language-go",
      "bookmarks",
      "language-todo",
      "spell-check",
      "styleguide",
      "autocomplete-paths",
      "linter-csslint",
      "autocomplete-plus",
      "autocomplete-snippets",
      "markdown-format"
    ],
    "audioBeep": false,
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-python, v0.5.3
autocomplete-ruby, v0.1.0
language-multimarkdown, v0.0.0
language-textile, v0.2.0
linter, v1.2.4
linter-jshint, v1.1.4
linter-tidy, v1.0.1
markdown-scroll-sync, v0.4.0
remote-edit, v1.8.14
tidy-markdown, v1.0.0

# Dev
No dev packages
```

**Comment by notslang** [comment]
what is the content of your file?

**Comment by DaveEveritt** [comment]
Hmmm. After a second restart the error stopped. The file was straight Markdown with headings, links, images and an horizontal rule. I'd also just disabled markdown-format, and had closed the preview pane. But two restarts? So now closing, as no longer an issue.

For reference, here's a grab of the markdown file at the time of the error:
![atom-tidy-markdown-error](https://cloud.githubusercontent.com/assets/101495/8916818/e87e02c6-34a5-11e5-81b0-5be4b50e2286.png)
