### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getGrammar' of undefined

### ISSUE THREAD

**Issue by mbrav** [slang800/atom-tidy-markdown#22]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [tidy-markdown](https://github.com/slang800/atom-tidy-markdown) package, v1.0.0
### Stack Trace

Uncaught TypeError: Cannot read property 'getGrammar' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:809

TypeError: Cannot read property 'getGrammar' of undefined
  at Object.module.exports.run (/Users/DaVinci/.atom/packages/tidy-markdown/lib/index.coffee:46:14)
  at /Users/DaVinci/.atom/packages/tidy-markdown/lib/index.coffee:30:12
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:767:18)
  at /Users/DaVinci/.atom/packages/tidy-markdown/lib/index.coffee:28:14
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1012:20)
  at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1004:19)
  at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:584:26)
  at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:547:18)
  at Object.module.exports.autosavePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autosave/lib/autosave.js:64:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autosave/lib/autosave.js:29:26
  at atom-pane.PaneElement.activeItemChanged (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:165:25)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:250:22)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:314:21)
  at tabs-tab.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:210:24)
  at space-pen-ul.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-ul.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```
### Commands

```
     -1:25.1.0 editor:newline (atom-text-editor.editor.is-focused)
  4x -1:24.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:21.3.0 editor:newline (atom-text-editor.editor.is-focused)
  6x -1:19.9.0 core:undo (atom-text-editor.editor.is-focused)
  8x -1:13.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:26.4.0 grammar-selector:show (atom-text-editor.editor)
     -0:23.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:23.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -0:19.9.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:16 core:undo (atom-text-editor.editor.is-focused)
     -0:13.9.0 grammar-selector:show (atom-text-editor.editor)
     -0:12 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:08.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:06.7.0 core:undo (atom-text-editor.editor.is-focused)
  3x -0:04.0 core:backspace (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "solarized-light-syntax"
    ],
    "disabledPackages": [
      "pigments",
      "language-go",
      "language-make",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-ruby",
      "language-ruby-on-rails",
      "language-shellscript",
      "language-source",
      "language-sql",
      "language-xml",
      "language-yaml",
      "language-toml",
      "language-todo",
      "link",
      "language-csharp"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-material-ui, v0.6.1
color-picker, v2.0.12
language-arduino, v0.3.1
processing-language, v0.2.0
tidy-markdown, v1.0.0

# Dev
No dev packages
```

**Comment by ChildishGiant** [comment]
Have it on linux aswell. constantly.
Stack Trace:
`TypeError: Cannot read property 'getGrammar' of undefined
    at TidyMarkdown.run (/home/solarpolarman/.atom/packages/tidy-markdown/lib/index.coffee:37:14)
    at /home/solarpolarman/.atom/packages/tidy-markdown/lib/index.coffee:21:12
    at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:811:18)
    at /home/solarpolarman/.atom/packages/tidy-markdown/lib/index.coffee:19:14
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1051:20)
    at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1043:19)
    at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app.asar/src/text-editor.js:629:26)
    at Pane.module.exports.Pane.saveItem (/usr/share/atom/resources/app.asar/src/pane.js:613:18)
    at Object.module.exports.autosavePaneItem (/usr/share/atom/resources/app.asar/node_modules/autosave/lib/autosave.js:64:21)
    at Object.module.exports.autosaveAllPaneItems (/usr/share/atom/resources/app.asar/node_modules/autosave/lib/autosave.js:75:28)
    at /usr/share/atom/resources/app.asar/node_modules/autosave/lib/autosave.js:27:26`
