### ISSUE TITLE
Uncaught while scanning an alias  on line 1, column 1expected alphabetic or numeric character b...

### ISSUE THREAD

**Issue by stanidesis** [slang800/atom-tidy-markdown#26]
[Enter steps to reproduce below:]

Not sure which line of my markdown caused the error.

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11.1
**Thrown From**: [tidy-markdown](https://github.com/slang800/atom-tidy-markdown) package, v1.0.0
### Stack Trace

Uncaught while scanning an alias
  on line 1, column 1
expected alphabetic or numeric character but found '*'
  on line 1, column 2

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:809

while scanning an alias
  on line 1, column 1
expected alphabetic or numeric character but found '*'
  on line 1, column 2
  at ScannerError.YAMLError (/Users/stanleyidesis/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/errors.js:70:46)
  at ScannerError.MarkedYAMLError (/Users/stanleyidesis/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/errors.js:90:45)
  at new ScannerError (/Users/stanleyidesis/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/scanner.js:23:49)
  at Constructor.Scanner.Scanner.scan_anchor (/Users/stanleyidesis/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/scanner.js:893:15)
  at Constructor.Scanner.Scanner.fetch_alias (/Users/stanleyidesis/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/scanner.js:522:36)
  at Constructor.Scanner.Scanner.fetch_more_tokens (/Users/stanleyidesis/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/scanner.js:217:21)
  at Constructor.Scanner.Scanner.check_token (/Users/stanleyidesis/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/scanner.js:115:14)
  at Constructor.Parser.Parser.parse_implicit_document_start (/Users/stanleyidesis/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/parser.js:125:17)
  at Constructor.Parser.Parser.check_event (/Users/stanleyidesis/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/parser.js:61:48)
  at Constructor.Composer.Composer.get_single_node (/Users/stanleyidesis/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/composer.js:50:17)
  at Constructor.BaseConstructor.BaseConstructor.get_single_data (/Users/stanleyidesis/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/constructor.js:76:19)
  at Object.load (/Users/stanleyidesis/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/yaml.js:112:20)
  at parse (/Users/stanleyidesis/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/index.js:28:27)
  at extractor (/Users/stanleyidesis/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/index.js:21:34)
  at module.exports (/Users/stanleyidesis/.atom/packages/tidy-markdown/node_modules/tidy-markdown/lib/index.coffee:274:13)
  at Object.module.exports.run (/Users/stanleyidesis/.atom/packages/tidy-markdown/lib/index.coffee:49:17)
  at /Users/stanleyidesis/.atom/packages/tidy-markdown/lib/index.coffee:30:12
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:767:18)
  at /Users/stanleyidesis/.atom/packages/tidy-markdown/lib/index.coffee:28:14
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1012:20)
  at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1004:19)
  at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:584:26)
  at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:547:18)
  at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:530:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:609:35)
  at atom-workspace.atom.commands.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace-element.js:293:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```
### Commands

```
     -3:44.8.0 application:add-project-folder (div.settings-view.pane-item)
     -0:01.4.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-dark-syntax"
    ]
  },
  "tidy-markdown": {
    "ensureFirstHeaderIsH1": false
  }
}
```
### Installed Packages

``` coffee
# User
linter-write-good, v0.6.1
markdown-preview-plus, v2.2.2
tidy-markdown, v1.0.0
typewriter, v0.3.4

# Dev
No dev packages
```

**Comment by notslang** [comment]
closing because this seems to be the same problem as https://github.com/slang800/atom-tidy-markdown/issues/35 (yaml errors)
