### ISSUE TITLE
Uncaught TypeError: this.character.charCodeAt is not a function

### ISSUE THREAD

**Issue by njaremko** [slang800/atom-tidy-markdown#27]
[Enter steps to reproduce below:]
1. Open a non-tidy markdown file and save

**Atom Version**: 1.1.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [tidy-markdown](https://github.com/slang800/atom-tidy-markdown) package, v1.0.0
### Stack Trace

Uncaught TypeError: this.character.charCodeAt is not a function

```
At C:\Users\jaremn\AppData\Local\atom\app-1.1.0\resources\app.asar\src\pane.js:788

TypeError: this.character.charCodeAt is not a function
  at ReaderError.ReaderError.toString (C:\Users\jaremn\.atom\packages\tidy-markdown\node_modules\tidy-markdown\node_modules\front-matter\node_modules\yaml-js\lib\reader.js:20:58)
  at ReaderError.YAMLError (C:\Users\jaremn\.atom\packages\tidy-markdown\node_modules\tidy-markdown\node_modules\front-matter\node_modules\yaml-js\lib\errors.js:70:25)
  at new ReaderError (C:\Users\jaremn\.atom\packages\tidy-markdown\node_modules\tidy-markdown\node_modules\front-matter\node_modules\yaml-js\lib\reader.js:16:41)
  at Constructor.Reader.Reader.check_printable (C:\Users\jaremn\.atom\packages\tidy-markdown\node_modules\tidy-markdown\node_modules\front-matter\node_modules\yaml-js\lib\reader.js:92:15)
  at Constructor.Reader (C:\Users\jaremn\.atom\packages\tidy-markdown\node_modules\tidy-markdown\node_modules\front-matter\node_modules\yaml-js\lib\reader.js:44:12)
  at Constructor.Loader (C:\Users\jaremn\.atom\packages\tidy-markdown\node_modules\tidy-markdown\node_modules\front-matter\node_modules\yaml-js\lib\loader.js:55:23)
  at Object.load (C:\Users\jaremn\.atom\packages\tidy-markdown\node_modules\tidy-markdown\node_modules\front-matter\node_modules\yaml-js\lib\yaml.js:111:15)
  at parse (C:\Users\jaremn\.atom\packages\tidy-markdown\node_modules\tidy-markdown\node_modules\front-matter\index.js:28:27)
  at extractor (C:\Users\jaremn\.atom\packages\tidy-markdown\node_modules\tidy-markdown\node_modules\front-matter\index.js:21:34)
  at module.exports (C:\Users\jaremn\.atom\packages\tidy-markdown\node_modules\tidy-markdown\lib\index.coffee:274:13)
  at Object.module.exports.run (C:\Users\jaremn\.atom\packages\tidy-markdown\lib\index.coffee:49:17)
  at C:\Users\jaremn\.atom\packages\tidy-markdown\lib\index.coffee:30:12
  at TextBuffer.module.exports.TextBuffer.transact (C:\Users\jaremn\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:765:18)
  at C:\Users\jaremn\.atom\packages\tidy-markdown\lib\index.coffee:28:14
  at Emitter.module.exports.Emitter.emit (C:\Users\jaremn\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\jaremn\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1010:20)
  at TextBuffer.module.exports.TextBuffer.save (C:\Users\jaremn\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1002:19)
  at TextEditor.module.exports.TextEditor.save (C:\Users\jaremn\AppData\Local\atom\app-1.1.0\resources\app.asar\src\text-editor.js:519:26)
  at Pane.module.exports.Pane.saveItem (C:\Users\jaremn\AppData\Local\atom\app-1.1.0\resources\app.asar\src\pane.js:529:18)
  at Pane.module.exports.Pane.saveActiveItem (C:\Users\jaremn\AppData\Local\atom\app-1.1.0\resources\app.asar\src\pane.js:512:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (C:\Users\jaremn\AppData\Local\atom\app-1.1.0\resources\app.asar\src\workspace.js:560:35)
  at atom-workspace.atom.commands.add.core:save (C:\Users\jaremn\AppData\Local\atom\app-1.1.0\resources\app.asar\src\workspace-element.js:270:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\jaremn\AppData\Local\atom\app-1.1.0\resources\app.asar\src\command-registry.js:243:29)
  at C:\Users\jaremn\AppData\Local\atom\app-1.1.0\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\jaremn\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:528:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\jaremn\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:351:22)
  at HTMLDocument.module.exports.WindowEventHandler.handleDocumentKeydown (C:\Users\jaremn\AppData\Local\atom\app-1.1.0\resources\app.asar\src\window-event-handler.js:97:20)

```
### Commands

```
     -1:11 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -1:10 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:13.5.0 core:save (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
color-picker, v2.0.13
tidy-markdown, v1.0.0
vim-mode, v0.62.0

# Dev
No dev packages
```

**Comment by notslang** [comment]
closing because this seems to be the same problem as https://github.com/slang800/atom-tidy-markdown/issues/35 (yaml errors)
