### ISSUE TITLE
Uncaught while scanning for the next tokenfound character ` that cannot start any token  on lin...

### ISSUE THREAD

**Issue by louis993546** [slang800/atom-tidy-markdown#29]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.2.1
**System**: Mac OS X 10.11
**Thrown From**: [tidy-markdown](https://github.com/slang800/atom-tidy-markdown) package, v1.0.0
### Stack Trace

Uncaught while scanning for the next token
found character ` that cannot start any token
  on line 3, column 31

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:825

while scanning for the next token
found character ` that cannot start any token
  on line 3, column 31
    at ScannerError.YAMLError [as constructor] (/Users/Louis/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/errors.js:70:46)
    at ScannerError.MarkedYAMLError [as constructor] (/Users/Louis/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/errors.js:90:45)
    at new ScannerError (/Users/Louis/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/scanner.js:23:49)
    at Constructor.global.Scanner.Scanner.fetch_more_tokens (/Users/Louis/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/scanner.js:240:13)
    at Constructor.global.Scanner.Scanner.check_token (/Users/Louis/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/scanner.js:115:14)
    at Constructor.global.Parser.Parser.parse_block_sequence_entry (/Users/Louis/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/parser.js:375:19)
    at Constructor.global.Parser.Parser.parse_block_sequence_first_entry (/Users/Louis/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/parser.js:368:19)
    at Constructor.global.Parser.Parser.check_event (/Users/Louis/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/parser.js:61:48)
    at Constructor.global.Composer.Composer.compose_sequence_node (/Users/Louis/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/composer.js:123:20)
    at Constructor.global.Composer.Composer.compose_node (/Users/Louis/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/composer.js:89:21)
```
### Commands

```
     -0:00.9.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
tidy-markdown, v1.0.0

# Dev
No dev packages
```

**Comment by notslang** [comment]
closing because this seems to be the same problem as https://github.com/slang800/atom-tidy-markdown/issues/35 (yaml errors)
