### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getGrammar' of undefined

### ISSUE THREAD

**Issue by bethdehart** [slang800/atom-tidy-markdown#31]
[Enter steps to reproduce below:]
1. Trying to update packages. I have the settings and .apmrc open. 

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.2
**Thrown From**: [tidy-markdown](https://github.com/slang800/atom-tidy-markdown) package, v1.0.0
### Stack Trace

Uncaught TypeError: Cannot read property 'getGrammar' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:829

TypeError: Cannot read property 'getGrammar' of undefined
    at Object.module.exports.run (/Users/ztw994/.atom/packages/tidy-markdown/lib/index.coffee:46:14)
    at /Users/ztw994/.atom/packages/tidy-markdown/lib/index.coffee:30:12
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:798:18)
    at /Users/ztw994/.atom/packages/tidy-markdown/lib/index.coffee:28:14
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1038:20)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1030:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:588:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:534:18)
    at Object.module.exports.autosavePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autosave/lib/autosave.js:64:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autosave/lib/autosave.js:29:26
    at atom-pane.PaneElement.activeItemChanged (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:152:25)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:248:22)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:316:21)
    at atom-tabs.TabBarView.onMouseDown (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:670:19)
```
### Commands

```
  2x -0:20 core:backspace (atom-text-editor.editor.is-focused)
     -0:16.5.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:03.8.0 core:undo (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "language-gfm",
      "language-gfm",
      "language-gfm",
      "markdown-preview-plus",
      "language-gfm",
      "language-gfm",
      "language-gfm",
      "language-gfm",
      "language-gfm",
      "language-gfm",
      "language-gfm",
      "language-gfm",
      "language-gfm",
      "language-gfm",
      "language-gfm"
    ],
    "openEmptyEditorOnStart": false
  }
}
```
### Installed Packages

``` coffee
# User
language-markdown, v0.7.1
markdown-scroll-sync, v2.0.3
tidy-markdown, v1.0.0

# Dev
No dev packages
```

**Comment by EQuimper** [comment]
+1
