### ISSUE TITLE
Uncaught expected '<document start>', but found <scalar>  on line 2, column 1

### ISSUE THREAD

**Issue by 521xueweihan** [slang800/atom-tidy-markdown#37]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.2
**Thrown From**: [tidy-markdown](https://github.com/slang800/atom-tidy-markdown) package, v1.0.0
### Stack Trace

Uncaught expected '<document start>', but found <scalar>
  on line 2, column 1

```
At /Users/sx/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:825

expected '<document start>', but found <scalar>
  on line 2, column 1
    at ParserError.YAMLError [as constructor] (/Users/sx/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/errors.js:70:46)
    at ParserError.MarkedYAMLError [as constructor] (/Users/sx/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/errors.js:90:45)
    at new ParserError (/Users/sx/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/parser.js:17:48)
    at Constructor.global.Parser.Parser.parse_document_start (/Users/sx/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/parser.js:152:17)
    at Constructor.global.Parser.Parser.check_event (/Users/sx/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/parser.js:61:48)
    at Constructor.global.Composer.Composer.get_single_node (/Users/sx/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/composer.js:53:17)
    at Constructor.global.BaseConstructor.BaseConstructor.get_single_data (/Users/sx/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/constructor.js:76:19)
    at Object.global.load (/Users/sx/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/yaml.js:112:20)
    at parse (/Users/sx/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/index.js:28:27)
    at extractor (/Users/sx/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/index.js:21:34)
    at module.exports (/Users/sx/.atom/packages/tidy-markdown/node_modules/tidy-markdown/lib/index.coffee:274:13)
    at Object.module.exports.run (/Users/sx/.atom/packages/tidy-markdown/lib/index.coffee:49:17)
    at /Users/sx/.atom/packages/tidy-markdown/lib/index.coffee:30:12
    at TextBuffer.module.exports.TextBuffer.transact (/Users/sx/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:805:18)
    at /Users/sx/.atom/packages/tidy-markdown/lib/index.coffee:28:14
    at Function.module.exports.Emitter.simpleDispatch (/Users/sx/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/sx/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Users/sx/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1045:20)
    at TextBuffer.module.exports.TextBuffer.save (/Users/sx/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1037:19)
    at TextEditor.module.exports.TextEditor.save (/Users/sx/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:630:26)
    at Pane.module.exports.Pane.saveItem (/Users/sx/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:545:18)
    at Pane.module.exports.Pane.saveActiveItem (/Users/sx/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:528:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Users/sx/Downloads/Atom.app/Contents/Resources/app.asar/src/workspace.js:649:35)
    at atom-workspace.commandRegistry.add.core:save (/Users/sx/Downloads/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:173:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/sx/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Users/sx/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/sx/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/sx/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Users/sx/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Users/sx/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
 25x -2:10.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:47.3.0 core:select-up (atom-text-editor.editor.is-focused)
     -1:45.1.0 markdown-themeable-pdf:export (atom-text-editor.editor.is-focused)
     -1:26.2.0 core:select-all (atom-text-editor.editor.is-focused)
     -1:25.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:18.1.0 tree-view:remove (li.file.entry.list-item.status-added.selected)
     -1:12.3.0 core:select-all (atom-text-editor.editor.is-focused)
  3x -1:11.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:05.2.0 markdown-themeable-pdf:export (atom-text-editor.editor.is-focused)
     -0:48.1.0 tree-view:copy (li.file.entry.list-item.status-added.selected)
     -0:45.6.0 tree-view:remove (span.name.icon.icon-file-pdf)
  3x -0:26.8.0 markdown-preview:toggle (atom-text-editor.editor.is-focused)
     -0:19.3.0 core:save-as (div.markdown-preview.native-key-bindings)
     -0:05.9.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:05.4.0 core:paste (atom-text-editor.editor.is-focused)
  3x -0:01.6.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "markdown-writer",
      "markdown-pdf",
      "markdown-themeable-pdf"
    ],
    "ignoredNames": [
      ".idea",
      "*.pyc"
    ],
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atomatigit, v1.5.5
autocomplete-python, v1.5.1
language-diff, v0.4.0
markdown-scroll-sync, v2.0.3
minimap, v4.19.0
seti-icons, v0.4.5
sync-settings, v0.6.0
tidy-markdown, v1.0.0

# Dev
No dev packages
```

**Comment by notslang** [comment]
Could you post the contents of the document from when you got this error?

**Comment by 521xueweihan** [comment]
Thank you for you replay. sorry I rewrite this document at last.So I can show it again.
The atom-tidy-markdown is  very useful,Thank you

**Comment by notslang** [comment]
pretty sure I fixed this in https://github.com/slang800/tidy-markdown/commit/03c918fec065a0fcc9d00b7062af267bfcd81136
