### ISSUE TITLE
Uncaught expected '<document start>', but found <scalar>  on line 9, column 1

### ISSUE THREAD

**Issue by vj--** [slang800/atom-tidy-markdown#38]
[Enter steps to reproduce below:]
1. Open existing .md file
2. CMD + Shift + P -> Tidy Markdown: Run

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [tidy-markdown](https://github.com/slang800/atom-tidy-markdown) package, v1.0.0
### Stack Trace

Uncaught expected '<document start>', but found <scalar>
  on line 9, column 1

```
At /Users/vj/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/parser.js:152

expected '<document start>', but found <scalar>
  on line 9, column 1
    at ParserError.YAMLError [as constructor] (/Users/vj/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/errors.js:70:46)
    at ParserError.MarkedYAMLError [as constructor] (/Users/vj/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/errors.js:90:45)
    at new ParserError (/Users/vj/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/parser.js:17:48)
    at Constructor.global.Parser.Parser.parse_document_start (/Users/vj/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/parser.js:152:17)
    at Constructor.global.Parser.Parser.check_event (/Users/vj/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/parser.js:61:48)
    at Constructor.global.Composer.Composer.get_single_node (/Users/vj/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/composer.js:53:17)
    at Constructor.global.BaseConstructor.BaseConstructor.get_single_data (/Users/vj/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/constructor.js:76:19)
    at Object.global.load (/Users/vj/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/yaml.js:112:20)
    at parse (/Users/vj/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/index.js:28:27)
    at extractor (/Users/vj/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/index.js:21:34)
    at module.exports (/Users/vj/.atom/packages/tidy-markdown/node_modules/tidy-markdown/lib/index.coffee:274:13)
    at Object.module.exports.run (/Users/vj/.atom/packages/tidy-markdown/lib/index.coffee:49:17)
    at atom-workspace.subscriptions.add.atom.commands.add.tidy-markdown:run (/Users/vj/.atom/packages/tidy-markdown/lib/index.coffee:20:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -4:21.2.0 core:undo (atom-text-editor.editor.is-focused.vim-mode.normal-mode)
     -4:10 tree-view:toggle (atom-text-editor.editor.is-focused.vim-mode.normal-mode)
     -4:04.5.0 command-palette:toggle (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -4:02.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -4:00.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:00.7.0 tidy-markdown:run (atom-text-editor.editor.vim-mode.normal-mode)
  2x -2:14.7.0 core:close (div.pane-item.native-key-bindings.about)
     -0:11.1.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:09.4.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:09.4.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:07.9.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:05.3.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:05.3.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:04.1.0 command-palette:toggle (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:00.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.8.0 tidy-markdown:run (atom-text-editor.editor.vim-mode.normal-mode)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "term2"
    ],
    "themes": [
      "nucleus-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Zen, v0.16.4
emmet, v2.4.1
language-swift, v0.4.0
linter, v1.11.3
minimap, v4.19.0
nucleus-dark-ui, v0.7.10
nuclide-installer, vundefined
tidy-markdown, v1.0.0
vim-mode, v0.64.0
vim-surround, v0.8.1

# Dev
No dev packages
```

**Comment by vj--** [comment]
Seems to be the existing markdown file, I created is messed up, and that is causing it... I will try to sanitize it and post the file if I can.

**Comment by notslang** [comment]
pretty sure I fixed this in https://github.com/slang800/tidy-markdown/commit/03c918fec065a0fcc9d00b7062af267bfcd81136
