### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by fthoms** [slang800/atom-tidy-markdown#40]
## Atom for windows v. 1.5.4

Error output from atom package manager:

```
Installing “tidy-markdown@2.0.0” failed.Hide output…

npm WARN addRemoteGit Error: Command failed: 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:658:15)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:98:17)
npm WARN addRemoteGit     at maybeClose (child_process.js:766:16)
npm WARN addRemoteGit     at Socket.<anonymous> (child_process.js:979:11)
npm WARN addRemoteGit     at Socket.emit (events.js:95:17)
npm WARN addRemoteGit     at Pipe.close (net.js:466:12)
npm WARN addRemoteGit  git://github.com/slang800/tidy-markdown.git#v1.0.0 resetting remote C:\Users\bc0631\.atom\.apm\_git-remotes\git-github-com-slang800-tidy-markdown-git-d58b5c28 because of error: { [Error: Command failed: ] killed: false, code: 1, signal: null }
npm ERR! git clone --template=C:\Users\bc0631\.atom\.apm\_git-remotes\_templates --mirror git://github.com/slang800/tidy-markdown.git C:\Users\bc0631\.atom\.apm\_git-remotes\git-github-com-slang800-tidy-markdown-git-d58b5c28: Cloning into bare repository 'C:\Users\bc0631\.atom\.apm\_git-remotes\git-github-com-slang800-tidy-markdown-git-d58b5c28'...
npm ERR! git clone --template=C:\Users\bc0631\.atom\.apm\_git-remotes\_templates --mirror git://github.com/slang800/tidy-markdown.git C:\Users\bc0631\.atom\.apm\_git-remotes\git-github-com-slang800-tidy-markdown-git-d58b5c28: fatal: unable to connect to github.com:
npm ERR! git clone --template=C:\Users\bc0631\.atom\.apm\_git-remotes\_templates --mirror git://github.com/slang800/tidy-markdown.git C:\Users\bc0631\.atom\.apm\_git-remotes\git-github-com-slang800-tidy-markdown-git-d58b5c28: github.com[0: 192.30.252.130]: errno=Result too large
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\bc0631\\AppData\\Local\\atom\\app-1.5.4\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\bc0631\\AppData\\Local\\atom\\app-1.5.4\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\bc0631\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\bc0631\\.atom\\.apmrc" "install" "C:\\Users\\bc0631\\AppData\\Local\\Temp\\d-116210-5528-16l1kkg\\package.tgz" "--target=0.34.5" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 128

npm ERR! Command failed: Cloning into bare repository 'C:\Users\bc0631\.atom\.apm\_git-remotes\git-github-com-slang800-tidy-markdown-git-d58b5c28'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.130]: errno=Result too large
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by notslang** [comment]
`Result too large`? That's an odd error, but the line before it says `fatal: unable to connect to github.com`, so I suspect that this is either the same issue as #32 or you just had a network error when you were installing.

@fthoms could you try doing `git clone git@github.com:slang800/atom-tidy-markdown.git` and see if that works?

**Comment by notslang** [comment]
Closing due to inactivity... This has probably been fixed within atom.
