### ISSUE TITLE
Uncaught expected '<document start>', but found <scalar>  on line 5, column 1

### ISSUE THREAD

**Issue by tas50** [slang800/atom-tidy-markdown#43]
[Enter steps to reproduce below:]
1. Attempt to save this markdown content:
   https://gist.github.com/tas50/8460dd13c728bd9b242b937125f6edc7
2. Error

**Atom Version**: 1.6.2
**System**: Mac OS X 10.11.4
**Thrown From**: [tidy-markdown](https://github.com/slang800/atom-tidy-markdown) package, v2.0.0
### Stack Trace

Uncaught expected '<document start>', but found <scalar>
  on line 5, column 1

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:896

expected '<document start>', but found <scalar>
  on line 5, column 1
    at ParserError.YAMLError [as constructor] (/Users/tsmith/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/errors.js:70:46)
    at ParserError.MarkedYAMLError [as constructor] (/Users/tsmith/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/errors.js:90:45)
    at new ParserError (/Users/tsmith/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/parser.js:17:48)
    at Constructor.global.Parser.Parser.parse_document_start (/Users/tsmith/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/parser.js:152:17)
    at Constructor.global.Parser.Parser.check_event (/Users/tsmith/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/parser.js:61:48)
    at Constructor.global.Composer.Composer.get_single_node (/Users/tsmith/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/composer.js:53:17)
    at Constructor.global.BaseConstructor.BaseConstructor.get_single_data (/Users/tsmith/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/constructor.js:76:19)
    at Object.global.load (/Users/tsmith/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/yaml.js:112:20)
    at parse (/Users/tsmith/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/index.js:28:27)
    at extractor (/Users/tsmith/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/index.js:21:34)
    at module.exports (/Users/tsmith/.atom/packages/tidy-markdown/node_modules/tidy-markdown/lib/index.coffee:138:13)
    at Object.module.exports.run (/Users/tsmith/.atom/packages/tidy-markdown/lib/index.coffee:49:17)
    at /Users/tsmith/.atom/packages/tidy-markdown/lib/index.coffee:30:12
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:811:18)
    at /Users/tsmith/.atom/packages/tidy-markdown/lib/index.coffee:28:14
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1051:20)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1043:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:629:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:613:18)
    at Pane.module.exports.Pane.promptToSaveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:585:23)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:531:18)
    at Pane.module.exports.Pane.destroyActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:512:12)
    at Workspace.module.exports.Workspace.destroyActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:681:35)
    at Workspace.module.exports.Workspace.closeActivePaneItemOrEmptyPaneOrWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:720:21)
    at atom-workspace.commandRegistry.add.core:close (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:202:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
```
### Commands

```
  2x -0:03.6.0 core:close (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "linter-foodcritic"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-plus, v2.29.2
language-chef, v0.9.0
language-dotfiles, v0.2.0
language-syslog-ng, v0.0.6
linter, v1.11.4
linter-checkbashisms, v0.1.5
linter-js-yaml, v1.2.5
linter-rubocop, v0.4.7
minimap, v4.21.0
pretty-json, v1.0.3
tidy-markdown, v2.0.0

# Dev
No dev packages
```

**Comment by notslang** [comment]
pretty sure I fixed this in https://github.com/slang800/tidy-markdown/commit/03c918fec065a0fcc9d00b7062af267bfcd81136

**Comment by tas50** [comment]
Thanks
