### ISSUE TITLE
Uncaught Error: cannot detect nodeType

### ISSUE THREAD

**Issue by Cabalist** [slang800/atom-tidy-markdown#47]
[Enter steps to reproduce below:]
1. Enter the following valid markdown.

```
> Some Text

<!-- Spacer -->
> Some Text I don't in the same section as above
```

It should render as:

```
> Some Text

<!-- Spacer -->
> Some Text I don't in the same section as above
```
1. Run Tidy Markdown
2. Get "Cannot detect nodeType" Error

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [tidy-markdown](https://github.com/slang800/atom-tidy-markdown) package, v3.0.0
### Stack Trace

Uncaught Error: cannot detect nodeType

```
At /Users/work/.atom/packages/tidy-markdown/node_modules/tidy-markdown/lib/utils.coffee:46

Error: cannot detect nodeType
    at nodeType (/Users/work/.atom/packages/tidy-markdown/node_modules/tidy-markdown/lib/utils.coffee:46:15)
    at bfsOrder (/Users/work/.atom/packages/tidy-markdown/node_modules/tidy-markdown/lib/index.coffee:84:10)
    at module.exports (/Users/work/.atom/packages/tidy-markdown/node_modules/tidy-markdown/lib/index.coffee:260:11)
    at TidyMarkdown.run (/Users/work/.atom/packages/tidy-markdown/lib/index.coffee:40:17)
    at atom-workspace.TidyMarkdown.subscriptions.add.atom.commands.add.tidy-markdown:run (/Users/work/.atom/packages/tidy-markdown/lib/index.coffee:11:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1100:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:314:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```
### Commands

```
     -2:21.9.0 tidy-markdown:run (atom-text-editor.editor.is-focused)
     -2:17.9.0 core:move-right (atom-text-editor.editor.is-focused)
     -2:17.5.0 core:select-down (atom-text-editor.editor.is-focused)
     -2:17.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:16.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:15.9.0 core:move-left (atom-text-editor.editor.is-focused)
 18x -2:14.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:48.8.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:46.5.0 tidy-markdown:run (atom-text-editor.editor.is-focused)
     -1:40.3.0 core:select-all (atom-text-editor.editor.is-focused)
     -1:39.9.0 core:copy (atom-text-editor.editor.is-focused)
     -0:10.7.0 application:new-file (atom-text-editor.editor.is-focused)
     -0:09.6.0 core:paste (atom-text-editor.editor.is-focused)
     -0:05.7.0 grammar-selector:show (atom-text-editor.editor)
     -0:04.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.1.0 tidy-markdown:run (a.inline-block)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
linter-markdown, v1.5.0
tabular, v0.1.0
tidy-markdown, v3.0.0

# Dev
No dev packages
```

**Comment by notslang** [comment]
working on this in https://github.com/slang800/tidy-markdown/pull/29

**Comment by Cabalist** [comment]
my bad!  Thanks. 👍
