### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getGrammar' of undefined

### ISSUE THREAD

**Issue by Raziyehbazargan** [slang800/atom-tidy-markdown#55]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.9.2
**System**: Mac OS X 10.11.6
**Thrown From**: [tidy-markdown](https://github.com/slang800/atom-tidy-markdown) package, v3.0.1
### Stack Trace

Uncaught TypeError: Cannot read property 'getGrammar' of undefined

```
At /Users/Raziyeh/Desktop/AllCourses/Learning Videos/Text Editors/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:852

TypeError: Cannot read property 'getGrammar' of undefined
    at TidyMarkdown.run (/Users/Raziyeh/.atom/packages/tidy-markdown/lib/index.coffee:37:14)
    at /Users/Raziyeh/.atom/packages/tidy-markdown/lib/index.coffee:21:12
    at TextBuffer.module.exports.TextBuffer.transact (/Users/Raziyeh/Desktop/AllCourses/Learning Videos/Text Editors/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:847:18)
    at /Users/Raziyeh/.atom/packages/tidy-markdown/lib/index.coffee:19:14
    at Function.module.exports.Emitter.simpleDispatch (/Users/Raziyeh/Desktop/AllCourses/Learning Videos/Text Editors/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/Raziyeh/Desktop/AllCourses/Learning Videos/Text Editors/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Users/Raziyeh/Desktop/AllCourses/Learning Videos/Text Editors/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1113:20)
    at TextBuffer.module.exports.TextBuffer.save (/Users/Raziyeh/Desktop/AllCourses/Learning Videos/Text Editors/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1105:19)
    at TextEditor.module.exports.TextEditor.save (/Users/Raziyeh/Desktop/AllCourses/Learning Videos/Text Editors/Atom.app/Contents/Resources/app.asar/src/text-editor.js:743:26)
    at /Users/Raziyeh/.atom/packages/markdown-document/lib/markdown-document-view.coffee:251:16
    at Function.module.exports.Emitter.simpleDispatch (/Users/Raziyeh/Desktop/AllCourses/Learning Videos/Text Editors/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/Raziyeh/Desktop/AllCourses/Learning Videos/Text Editors/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Users/Raziyeh/Desktop/AllCourses/Learning Videos/Text Editors/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1399:25
```
### Commands

```
     -0:57.9.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:57.9.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:28.7.0 core:backspace (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "language-gfm"
    ],
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-bootstrap3, v1.2.12 (inactive)
atom-markdown-wrapper, v4.0.0 (inactive)
emmet, v2.3.16 (active)
highlight-selected, v0.11.1 (active)
language-markdown, v0.16.1 (active)
linter, v1.11.3 (active)
linter-eslint, v5.2.6 (active)
markdown-document, v0.2.0 (active)
markdown-pdf, v1.5.0 (inactive)
minimap, v4.16.2 (active)
open-in-browser, v0.4.6 (inactive)
pp-markdown, v0.0.2 (active)
source-preview, v0.5.0 (inactive)
source-preview-markdown, v0.1.1 (active)
tidy-markdown, v3.0.1 (active)
atom-dark-syntax, v0.27.0 (active)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.1 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.0 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (inactive)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by sdaugherty** [comment]
Also getting this when choosing tidy-markdown from the packages menu

**Atom Version**: 1.9.6
**System**: Microsoft Windows 10 Pro
**Thrown From**: [tidy-markdown](https://github.com/slang800/atom-tidy-markdown) package, v3.0.1

### Stack Trace

Uncaught TypeError: Cannot read property 'getGrammar' of undefined

```
At /C:/Users/steph/.atom/packages/tidy-markdown/lib/index.coffee:57

TypeError: Cannot read property 'getGrammar' of undefined
    at TidyMarkdown.run (file:///C:/Users/steph/.atom/packages/tidy-markdown/lib/index.coffee:37:14)
    at atom-workspace.TidyMarkdown.subscriptions.add.atom.commands.add.tidy-markdown:run (file:///C:/Users/steph/.atom/packages/tidy-markdown/lib/index.coffee:11:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\steph\AppData\Local\atom\app-1.9.6\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\steph\AppData\Local\atom\app-1.9.6\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\steph\AppData\Local\atom\app-1.9.6\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\steph\AppData\Local\atom\app-1.9.6\resources\app.asar\src\atom-environment.js:1104:28)
    at EventEmitter.outerCallback (C:\Users\steph\AppData\Local\atom\app-1.9.6\resources\app.asar\src\application-delegate.js:327:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
```

### Commands

```
     -3:25 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:05.4.0 tidy-markdown:run (atom-text-editor.editor.mini.is-focused)
```

### Config

``` json
{
  "core": {
    "disabledPackages": [
      "language-gfm",
      "markdown-preview",
      "atom-xsltransform"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
atom-beautify, v0.29.10 (inactive)
atom-xsltransform, v0.8.0 (inactive)
color-picker, v2.2.2 (active)
editing-diff, v0.2.1 (active)
git-control, v0.8.2 (inactive)
git-time-machine, v1.5.3 (inactive)
github-issues, v0.7.1 (active)
github-plus, v1.0.0 (inactive)
imdone-atom-github, v0.1.11 (active)
language-gfm2, v0.92.2 (active)
language-liquid, v0.5.1 (active)
language-markdown, v0.16.1 (active)
language-mediawiki, v2.2.0 (active)
language-sln, v0.1.0 (active)
markdown-folder, v0.5.0 (inactive)
markdown-preview-plus, v2.4.0 (active)
markdown-scroll-sync, v2.1.2 (active)
markdown-toc, v0.4.1 (inactive)
markdown-writer, v2.5.1 (inactive)
minimap, v4.24.7 (active)
pandoc-convert, v1.1.0 (active)
pigments, v0.31.2 (active)
table-editor, v0.2.0 (active)
tidy-markdown, v3.0.1 (active)
tool-bar-markdown-writer, v0.2.0 (active)
visualstudio-terminals, v0.7.0 (active)
xml-formatter, v0.10.0 (inactive)
xml-tools, v0.2.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (active)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.3 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (inactive)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (inactive)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```
