### ISSUE TITLE
Uncaught TypeError: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by gmathieu** [slang800/atom-tidy-markdown#6]
[Enter steps to reproduce below:]
1. ran tidy markdown run for the first time on basic markdown file

**Atom Version**: 0.188.0
**System**: Mac OS X 10.10.2
**Thrown From**: [tidy-markdown](https://github.com/slang800/atom-tidy-markdown) package, v0.1.1
### Stack Trace

Uncaught TypeError: Cannot read property 'trim' of undefined

```
At /Users/guillaume/.atom/packages/tidy-markdown/node_modules/tidy-markdown/lib/index.coffee:253

TypeError: Cannot read property 'trim' of undefined
  at module.exports (/Users/guillaume/.atom/packages/tidy-markdown/node_modules/tidy-markdown/lib/index.coffee:253:50)
  at TidyMarkdown.run (/Users/guillaume/.atom/packages/tidy-markdown/lib/tidy-markdown.coffee:36:17)
  at atom-workspace.<anonymous> (/Users/guillaume/.atom/packages/tidy-markdown/lib/tidy-markdown.coffee:13:10)
  at atom-workspace.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:242:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:242:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:180:20)

```
### Commands

```
     -1:22.7 core:move-up (atom-text-editor.editor.is-focused)
     -1:22.5 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
     -1:22.4 core:move-up (atom-text-editor.editor.is-focused)
     -1:22.2 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
     -1:21.9 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  2x -1:21.6 core:move-up (atom-text-editor.editor.is-focused)
     -1:21.2 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
  2x -1:20.9 core:move-up (atom-text-editor.editor.is-focused)
     -1:20.3 core:backspace (atom-text-editor.editor.is-focused)
     -1:18.4 core:move-to-top (atom-text-editor.editor.is-focused)
     -1:17.5 core:save (atom-text-editor.editor.is-focused)
     -1:15.8 settings-view:open (atom-text-editor.editor.is-focused)
     -1:11.1 core:confirm (atom-text-editor.editor.mini)
     -0:03.1 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:01.0 core:confirm (atom-text-editor.editor.mini)
     -0:01.0 tidy-markdown:run (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
linter, v0.12.0
monokai, v0.12.0
save-session, v0.12.3
tidy-markdown, v0.1.1

# Dev
No dev packages
```

**Comment by notslang** [comment]
pushed a new version that should fix this: https://github.com/slang800/atom-tidy-markdown/releases/tag/v0.2.0 ... reopen if you still have this problem
