### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getGrammar' of undefined

### ISSUE THREAD

**Issue by jessehersch** [slang800/atom-tidy-markdown#78]
I am just trying out atom and ran into this. May be doing something wrong?

1. open a markdown file
2. view->developer->toggle developer tools (just to get the error details)
3. packages->tidy markdown
4. observe the fail

**Atom**: 1.55.0 x64
**Electron**: 6.1.12
**OS**: Ubuntu 18.04.5
**Thrown From**: [tidy-markdown](https://github.com/slang800/atom-tidy-markdown) package 3.0.1

### Stack Trace

Uncaught TypeError: Cannot read property 'getGrammar' of undefined

```
At /home/jhersch/.atom/packages/tidy-markdown/lib/index.coffee:37

TypeError: Cannot read property 'getGrammar' of undefined
    at TidyMarkdown.run (/packages/tidy-markdown/lib/index.coffee:37:15)
    at /packages/tidy-markdown/lib/index.coffee:11:32)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:350382)
    at CommandRegistry.dispatch (/usr/share/atom/resources/app/static/<embedded>:11:348857)
    at AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app/static/<embedded>:1:727610)
    at EventEmitter.t (/usr/share/atom/resources/app/static/<embedded>:1:735578)
    at EventEmitter.emit (events.js:200:13)
    at Object.onMessage (/usr/share/atom/resources/electron.asar/renderer/init.js:42:16)
```

### Commands

```
     -8:31.5.0 core:save (input.hidden-input)
     -8:23.2.0 tidy-markdown:run (input.hidden-input)
  4x -6:35.5.0 markdown-preview-plus:toggle (input.hidden-input)
     -5:38 command-palette:toggle (input.hidden-input)
     -5:33.1.0 tidy-markdown:run (input.hidden-input)
     -1:59.4.0 window:toggle-dev-tools (div.panels-item)
     -1:09.3.0 tidy-markdown:run (input.hidden-input)
```

### Non-Core Packages

```
language-markdown 0.37.0 
markdown-preview-plus 4.9.2 
markdown-writer 2.11.11 
tidy-markdown 3.0.1 
```

**Comment by jessehersch** [comment]
oops looks like this is a dup of a 1 year old bug:
https://github.com/notslang/atom-tidy-markdown/issues/77

I guess this is not maintained anymore. will uninstall.

**Comment by notslang** [comment]
Yeah, sorry - I switched to using vim so I probably won't be maintaining this.
